comments_space: # From https://github.com/brandenr/swiftlintconfig
  name: "Space After Comment"
  regex: '(^ *//\w+)'
  message: "There should be a space after //"
  severity: error

force_https: # From https://github.com/Twigz/Game
  name: "Force HTTPS over HTTP"
  regex: "((?i)http(?!s))"
  match_kinds: string
  message: "HTTPS should be favored over HTTP"
  severity: warning

double_space: # From https://github.com/IBM-Swift/Package-Builder
  include: "*.swift"
  name: "Double space"
  regex: '([a-z,A-Z] \s+)'
  message: "Double space between keywords"
  match_kinds: keyword
  severity: warning

disabled_rules: # rule identifiers to exclude from running
  #Errors
  - line_length
  - large_tuple
  - trailing_comma
  - function_body_length
  - identifier_name
  - empty_parentheses_with_trailing_closure
  #Would be good to get these back in
  - force_cast
  - force_try
  - type_name
  - closure_parameter_position
  - attributes
  - no_fallthrough_only

opt_in_rules: # some rules are only opt-in
  # Find all the available rules by running:
  # swiftlint rules
  - empty_count
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - first_where
  - sorted_imports
  - object_literal
  - number_separator
  - prohibited_super_call
  - fatal_error_message

included: # paths to include during linting. `--path` is ignored if present.

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Carthage
  - fastlane
